Sensors/Models/Groups/CreateGroupDTO.cs
using System.ComponentModel.DataAnnotations;

namespace Sensors.Models.Groups;

public class CreateGroupDTO
{
    [Required]
    public string Name { get; set; }

    public string? Description { get; set; }
}

Sensors/Models/Groups/DefaultInfoGroupDTO.cs
using System.ComponentModel.DataAnnotations;

namespace Sensors.Models.Groups
{
    public class DefaultInfoGroupDTO
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string? Description { get; set; }
    }
}

Sensors/Models/Groups/ListGroupDTO.cs
namespace Sensors.Models.Groups
{
    public class ListGroupDTO : DefaultInfoGroupDTO
    {
        public int Zones { get; set; }
    }
}

Sensors/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities;
using Sensors.Data;
using System.Security.Claims;
using Sensors.Models.Groups;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace Sensors.Controllers;

[Authorize]
public class GroupsController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly string _userId;

    public GroupsController(ApplicationDbContext context, IMapper mapper, IHttpContextAccessor httpContextAccessor)
    {
        _context = context;
        _mapper = mapper;
        _userId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
    }

    // GET: Groups
    public async Task<IActionResult> Index()
    {
        var groupZoneCounts = await _context.Groups.Select(g => new
        {
            Group = g,
            ZoneCount = _context.Zones.Count(z => z.GroupId == g.Id)
        }).Where(g => g.Group.UserId == _userId).ToListAsync();

        var listGroupDTOs = groupZoneCounts.Select(g => new ListGroupDTO() { Id = g.Group.Id, Name = g.Group.Name, Description = g.Group.Description, Zones = g.ZoneCount });
        return View(listGroupDTOs);
    }

    // GET: Groups/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null || _context.Groups == null)
        {
            return NotFound();
        }

        var @group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id && g.UserId == _userId);
        if (@group == null)
        {
            return NotFound();
        }
        DefaultInfoGroupDTO defaultInfoGroupDTO = _mapper.Map<DefaultInfoGroupDTO>(@group);

        return View(defaultInfoGroupDTO);
    }

    // GET: Groups/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Groups/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name,Description")] CreateGroupDTO groupDTO)
    {
        if (GroupExistsWithTheSameName(0, groupDTO.Name))
        {
            ModelState.AddModelError(String.Empty, "A group with the same name already exists!");
            return View(groupDTO);
        }

        if (ModelState.IsValid)
        {
            try
            {
                Group @group = _mapper.Map<Group>(groupDTO);
                @group.UserId = _userId;

                _context.Add(@group);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "An error occurred while saving the group. Please try again.");
            }
        }

        return View(groupDTO);
    }

    // GET: Groups/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null || _context.Groups == null)
        {
            return NotFound();
        }

        var @group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id && g.UserId == _userId);
        if (@group == null)
        {
            return NotFound();
        }

        DefaultInfoGroupDTO defaultInfoGroupDTO = _mapper.Map<DefaultInfoGroupDTO>(@group);

        return View(defaultInfoGroupDTO);
    }

    // POST: Groups/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Name,Description, Id")] DefaultInfoGroupDTO defaultInfoGroupDTO)
    {
        if (id != defaultInfoGroupDTO.Id)
        {
            return NotFound();
        }

        if (GroupExistsWithTheSameName(id, defaultInfoGroupDTO.Name))
        {
            ModelState.AddModelError(String.Empty, "A group with the same name already exists!");
            return View(defaultInfoGroupDTO);
        }

        if (ModelState.IsValid)
        {
            try
            {
                Group @group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id && g.UserId == _userId);
                if (null == @group)
                {
                    return NotFound();
                }

                @group.Name = defaultInfoGroupDTO.Name;
                @group.Description = defaultInfoGroupDTO.Description;

                _context.Update(@group);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                ModelState.AddModelError(String.Empty, "Update failed, please reload and try again!");
            }
            return RedirectToAction(nameof(Index));
        }

        return View(defaultInfoGroupDTO);
    }

    // GET: Groups/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null || _context.Groups == null)
        {
            return NotFound();
        }

        var @group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id && g.UserId == _userId);
        if (@group == null)
        {
            return NotFound();
        }

        DefaultInfoGroupDTO defaultInfoGroupDTO = _mapper.Map<DefaultInfoGroupDTO>(@group);

        return View(defaultInfoGroupDTO);
    }

    // POST: Groups/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        if (_context.Groups == null)
        {
            return Problem("Entity set 'ApplicationDbContext.Groups'  is null.");
        }
        var @group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == id && g.UserId == _userId);
        if (@group != null)
        {
            _context.Groups.Remove(@group);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool GroupExistsWithTheSameName(int id, string name)
    {
        bool groupExists = _context.Groups.Any(g => g.UserId == _userId && g.Id != id && g.Name == name);
        return groupExists;
    }
}

Sensors/Controllers/ZonesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Entities;
using Sensors.Data;
using System.Security.Claims;
using AutoMapper;
using Sensors.Helpers;
using Microsoft.AspNetCore.Authorization;
using Sensors.Models.Zones;

namespace Sensors.Controllers;

[Authorize]
public class ZonesController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IMapper _mapper;
    private readonly string _userId;

    public ZonesController(ApplicationDbContext context, IMapper mapper, IHttpContextAccessor httpContextAccessor)
    {
        _context = context;
        _mapper = mapper;
        _userId = httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
    }

    // List all Zones for a specific Group
    public async Task<IActionResult> Index(int groupId)
    {
        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;
        var zones = await _context.Zones.Where(z => z.GroupId == groupId).ToListAsync();
        return View(zones);
    }

    // GET: Zones/Details/5
    public async Task<IActionResult> Details(int groupId, int? id)
    {
        if (id == null || _context.Zones == null)
        {
            return NotFound();
        }

        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        var zone = await _context.Zones.FirstOrDefaultAsync(z => z.GroupId == groupId && z.Id == id);
        if (zone == null)
        {
            return NotFound();
        }

        return View(_mapper.Map<DefaultInfoZoneDTO>(zone));
    }

    // GET: Zones/Create
    public async Task<IActionResult> Create(int groupId)
    {
        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;
        return View();
    }

    // POST: Zones/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(int groupId, [Bind("Name,Description")] CreateZoneDTO createZoneDTO)
    {
        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        if (ZoneExistsWithTheSameName(groupId, 0, createZoneDTO.Name))
        {
            ModelState.AddModelError(String.Empty, "A zone with the same name already exists!");
            return View(createZoneDTO);
        }

        if (ModelState.IsValid)
        {
            try
            {
                Zone zone = _mapper.Map<Zone>(createZoneDTO);
                zone.GroupId = groupId;
                zone.ClientSecretKey = RandomStringGenerator.Generate();

                _context.Add(zone);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { groupId });
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "An error occurred while saving the zone. Please try again.");
            }
        }

        return View(createZoneDTO);
    }

    // GET: Zones/Edit/5
    public async Task<IActionResult> Edit(int groupId, int? id)
    {
        if (id == null || _context.Zones == null)
        {
            return NotFound();
        }

        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        var zone = await _context.Zones.FirstOrDefaultAsync(z => z.GroupId == groupId && z.Id == id);
        if (zone == null)
        {
            return NotFound();
        }

        return View(_mapper.Map<EditZoneDTO>(zone));
    }

    // POST: Zones/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int groupId, int id, [Bind("Id,Name,Description")] EditZoneDTO editZoneDTO)
    {
        if (id != editZoneDTO.Id)
        {
            return NotFound();
        }

        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        var zone = await _context.Zones.FirstOrDefaultAsync(z => z.GroupId == groupId && z.Id == id);
        if (zone == null)
        {
            return NotFound();
        }

        if (ZoneExistsWithTheSameName(groupId, editZoneDTO.Id, editZoneDTO.Name))
        {
            ModelState.AddModelError(string.Empty, "A zone with the same name already exists!");
            return View(editZoneDTO);
        }

        if (ModelState.IsValid)
        {
            try
            {
                zone.Name = editZoneDTO.Name;
                zone.Description = editZoneDTO.Description;
                _context.Update(zone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { groupId });
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "An error occurred while saving the zone. Please try again.");
            }
        }
        return View(editZoneDTO);
    }

    // GET: Zones/Delete/5
    public async Task<IActionResult> Delete(int groupId, int? id)
    {
        if (id == null || _context.Zones == null)
        {
            return NotFound();
        }

        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        var zone = await _context.Zones.FirstOrDefaultAsync(z => z.GroupId == groupId && z.Id == id);
        if (zone == null)
        {
            return NotFound();
        }

        return View(_mapper.Map<DefaultInfoZoneDTO>(zone));
    }

    // POST: Zones/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int groupId, int id)
    {
        if (_context.Zones == null)
        {
            return NotFound();
        }

        var group = await _context.Groups.FirstOrDefaultAsync(g => g.Id == groupId && g.UserId == _userId);

        if (group == null)
        {
            return NotFound();
        }

        ViewBag.Group = group;

        var zone = await _context.Zones.FirstOrDefaultAsync(z => z.GroupId == groupId && z.Id == id);
        if (zone == null)
        {
            return NotFound();
        }

        try
        {
            _context.Zones.Remove(zone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { groupId });
        }
        catch
        {
            ModelState.AddModelError(string.Empty, "An error occurred while deleting the zone. Please try again.");
        }

        return View(_mapper.Map<DefaultInfoZoneDTO>(zone));
    }

    private bool ZoneExistsWithTheSameName(int groupId, int zoneId, string name)
    {
        bool zoneExists = _context.Zones.Any(z => z.GroupId == groupId && z.Id != zoneId && z.Name == name);
        return zoneExists;
    }
}

Sensors/Views/Groups/Create.cshtml
@model Sensors.Models.Groups.CreateGroupDTO

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> 
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sensors/Views/Groups/Delete.cshtml
@model Sensors.Models.Groups.DefaultInfoGroupDTO

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

Sensors/Views/Groups/Details.cshtml
@model Sensors.Models.Groups.DefaultInfoGroupDTO

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Sensors/Views/Groups/Edit.cshtml
@model Sensors.Models.Groups.DefaultInfoGroupDTO

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Group</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" /> 
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sensors/Views/Groups/Index.cshtml
@model IEnumerable<Sensors.Models.Groups.ListGroupDTO>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Zones</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zones)
                </td>
                <td>
                    <a asp-area="" asp-action="Index"  asp-controller="Zones" asp-route-groupId="@item.Id">Zones</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>